version: '3.8'

services:
  n8n:
    image: n8nio/n8n:1.24.0
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password123
      - NODE_ENV=production
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678
      - N8N_ENCRYPTION_KEY=6ece9c201f8e4d5f8e3c1f6b9e8d7c5a4b3f2e1d0c9b8a7
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data: